#!/bin/sh

sudo dmesg -c > /dev/null

X=1024
Y=768
./vc -d /dev/video1 -c 10 -i 5 -s -j -x $X -y $Y $@

dmesg | grep uvcvideo > log

#cat log | grep -v VIDIOC_ENUM_FRAME | grep -v _QUERYBUF | grep -v uvc_v4l2_mmap | tail -35
